README.md

#What
データベース設計。
#Why
これからの実装の根幹となるため。
実装したい機能のを改めて認識する。

[WHIP] データベース設計

---

app/controllers/application_controller.rb
app/controllers/users_controller.rb
app/models/user.rb
config/routes.rb

[why]ユーザー新規登録とログイン機能実装の為
[what]
usersテーブル作成
devise導入
userコントローラーの作成

[WPI]user-login1

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/mypage.scss
app/views/posts/mypage.html.haml

最終課題　ユーザーページのビューの確認
ヘッダーとフッターは部分テンプレートを別で用意している
マージして良いかの確認をよろしくお願いいたします

[WIP]mypage-create

---

app/models/adress.rb
app/models/comment.rb
app/models/product.rb
app/models/user.rb
db/migrate/20200305012125_devise_create_users.rb
db/migrate/20200305075535_create_adresses.rb
db/migrate/20200305122543_create_comments.rb
db/migrate/20200305122602_create_products.rb
db/schema.rb
test/fixtures/comments.yml
test/fixtures/products.yml
test/models/comment_test.rb
test/models/product_test.rb

[why]
コメントと商品のテーブル作成
[what]
マイグレーションファイル作成
各モデルファイルにアソシエーションを記入

[WPI]Products&commentsテーブル作成

---

app/views/devise/registrations/new.html.haml
db/schema.rb

#What 
データベースのカラムの中で自分のローカルに反映していないものは、仮でnameとしておいてます。
#Why
サーバー側の作業の確認に使うため、mergeします

[WHIP]新規登録のビュー（仮)

---

config/routes.rb

root setting

---

app/assets/stylesheets/itemditail.scss
app/views/posts/itemditail.html.haml

#WHAT 
商品詳細ページビューの実装
#WHY
確認のお願いします

[WIP] item-ditail

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/modules/_new.scss
app/views/devise/registrations/new.html.haml
db/schema.rb

[What]
サインアップ画面のビュー
https://gyazo.com/f5e8f25bcf649ff823dd18f739a1b1d4
https://gyazo.com/047517395dfab80299a7c32ca346a983
[Why]
フォーマット作成のため

[WHIP]サインアップ　ビュー

---

app/assets/javascripts/products.coffee
app/assets/stylesheets/application.scss
app/assets/stylesheets/config/_variable.scss
app/assets/stylesheets/mixin/_mixins.scss
app/assets/stylesheets/modules/_products.scss
app/assets/stylesheets/products.scss
app/controllers/posts_controller.rb
app/controllers/products_controller.rb
app/helpers/products_helper.rb
app/models/product.rb
app/uploaders/image_uploader.rb
app/views/products/index.html.haml
app/views/products/new.html.haml
config/routes.rb
test/controllers/products_controller_test.rb

商品出品ページのマークアップです。
確認よろしくお願いします。
products/new.html.haml を作成しました。

products/new.html.haml Create

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/config/_variable.scss
app/assets/stylesheets/modules/_header.scss
app/controllers/application_controller.rb
app/views/posts/_header.html.haml
app/views/posts/_main.html.haml

ログイン状態とログアウト状態で表示されるビューを変更。
ヘッダー右側のリンクのパスを設定。

ログイン状態とログアウト状態

---

app/controllers/address_controller.rb
app/controllers/users/confirmations_controller.rb
app/controllers/users/omniauth_callbacks_controller.rb
app/controllers/users/passwords_controller.rb
app/controllers/users/registrations_controller.rb
app/controllers/users/sessions_controller.rb
app/controllers/users/unlocks_controller.rb
app/models/address.rb
app/views/devise/registrations/new.html.haml
app/views/devise/registrations/new_address.html.haml
config/routes.rb

wizard-create

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/modules/_buyer.scss
app/controllers/products_controller.rb
app/views/products/buyer.html.haml
config/routes.rb

購入確認画面のビュー

---

app/assets/stylesheets/product-index.scss
app/controllers/products_controller.rb
app/uploaders/image_uploader.rb
app/views/products/index.html.haml
app/views/products/show.html.haml

[why]
商品一覧に保存されているいちばんめのがぞうを表示
[what]
haml scssファイルと
minimagicのリサイズ変更

[WPI]商品一覧に画像を反映

---

app/assets/stylesheets/modules/_show.scss
app/views/products/index.html.haml
app/views/products/show.html.haml

[WHY]
商品詳細ページで登録された画像を表示
[WHAT]
haml とscssを編集
https://gyazo.com/7fe45f79fbed130feff56ec95d3767e6

[WPI]商品詳細画像表示

---

app/assets/javascripts/application.js
app/assets/javascripts/category.js
app/views/users/_header.html.haml

categoryEX

---

app/views/products/show.html.haml

[WHY]
商品詳細で投稿者は編集削除できる
商品詳細で投稿者以外は購入できる
[WHAT]
hamlを編集

[WPI]商品詳細ページ条件分岐完成

---

app/controllers/buyer_controller.rb
app/controllers/products_controller.rb
app/views/buyer/index.html.haml
app/views/buyer/veri.html.haml
app/views/products/show.html.haml
config/routes.rb

[WHY]
商品購入機能実装
[WHAT]
コントローラ　haml routeを編集
一覧→詳細→購入確認→購入完了

[WPI]verification

---

app/views/products/show.html.haml

[WHY]
一度買われた商品をかえないように
[WHAT]
hamlを修正

[WPI]soldout

---

Gemfile
Gemfile.lock
app/assets/stylesheets/_reset.scss
app/views/products/index.html.haml
app/views/products/show.html.haml
app/views/users/show.html.haml
config/breadcrumbs.rb

[WIP]breadcrumb-create

---

app/assets/stylesheets/modules/_show.scss
app/controllers/comments_controller.rb
app/controllers/products_controller.rb
app/views/products/show.html.haml
config/routes.rb

#WHAT 
コメント機能の実装
#WHY 
確認をよろしくお願いいたします

[WIP]コメント機能の実装

---

app/assets/javascripts/category2.js
app/controllers/products_controller.rb
config/routes.rb

[WIP]edit-comprate!!
